name: Test

on:
  push:
    paths:
      - '.github/workflows/**'
      - '**.go'
      - go.mod
      - Dockerfile

jobs:
  App:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up Go 1.13
        uses: actions/setup-go@master
        with:
          go-version: '1.13'

      - name: Install dependencies
        run: |
          go mod download
          go mod verify

      - name: Run tests
        run: |
          go test -v

  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up Go 1.13
        uses: actions/setup-go@master
        with:
          go-version: '1.13'

      - name: Run GolangCI-Lint
        uses: reviewdog/action-golangci-lint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

  Dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Run hadolint
        uses: reviewdog/action-hadolint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
